'use strict';
const selected=new Set();
const names=Object.fromEntries(CATEGORIES.flatMap(c=>c.items.map(i=>[i.id,i.name])));
let currentResults=[];
const byId=id=>document.getElementById(id);
function matchRecipes(ids){const chosen=new Set(ids);if(!chosen.size)return [];return RECIPES.map(r=>{const required=r.ingredients.map(i=>i.id);const missing=required.filter(id=>!chosen.has(id));const matched=required.length-missing.length;return {recipe:r,missing,matched,ratio:matched/required.length};}).filter(r=>r.matched>0&&r.missing.length<=1).sort((a,b)=>a.missing.length-b.missing.length||b.matched-a.matched||b.ratio-a.ratio||a.recipe.time-b.recipe.time||a.recipe.id.localeCompare(b.recipe.id));}
window.matchRecipes=matchRecipes;
function show(view,focusId){['selection','results','detail'].forEach(id=>byId(id).hidden=id!==view);window.scrollTo({top:0,behavior:'instant'});if(focusId)byId(focusId).focus({preventScroll:true});}
function updateSelection(){byId('selected-count').textContent=`${selected.size}個選択中`;byId('selection-summary').textContent=selected.size?`${selected.size}個の食材から、今日の一品を。`:'食材を選んで、今日の一品を。';byId('selection-message').textContent='';}
function renderIngredients(){const root=byId('categories');CATEGORIES.forEach(c=>{const section=document.createElement('div');section.className='category';const heading=document.createElement('h3');heading.textContent=c.name;section.append(heading);const grid=document.createElement('div');grid.className='ingredients';c.items.forEach(i=>{const button=document.createElement('button');button.className='ingredient';button.type='button';button.dataset.ingredient=i.id;button.setAttribute('aria-pressed','false');button.setAttribute('aria-label',i.name);button.innerHTML=`<span class="icon" aria-hidden="true">${i.icon}</span><span class="name">${i.name}</span><span class="check" aria-hidden="true"></span>`;button.addEventListener('click',()=>{if(selected.has(i.id))selected.delete(i.id);else selected.add(i.id);button.setAttribute('aria-pressed',String(selected.has(i.id)));button.querySelector('.check').textContent=selected.has(i.id)?'✓':'';updateSelection();});grid.append(button);});section.append(grid);root.append(section);});}
function statusText(result){return result.missing.length?`○ あと${result.missing.map(id=>names[id]).join('・')}があれば作れる`:'◎ 今あるもので作れる';}
function makeCard(result){const r=result.recipe;const button=document.createElement('button');button.type='button';button.className='card';button.dataset.recipe=r.id;button.setAttribute('aria-label',`${r.title}、${r.time}分、${statusText(result)}。レシピを見る`);button.innerHTML=`<img src="${r.image}" alt="${r.title}" width="600" height="400" loading="lazy"><div class="card-body"><span class="badge ${result.missing.length?'missing':''}">${statusText(result)}</span><h3>${r.title}</h3><div class="card-meta"><span>約${r.time}分</span><span>レシピを見る</span></div></div>`;button.addEventListener('click',()=>openDetail(result));return button;}
function searchRecipes(){if(!selected.size){byId('selection-message').textContent='冷蔵庫にある食材を選んでね';return;}currentResults=matchRecipes(selected);byId('result-selection').textContent=`選んだ食材：${[...selected].map(id=>names[id]).join('・')}`;const root=byId('result-content');root.replaceChildren();if(!currentResults.length){root.innerHTML='<div class="empty"><h2>ぴったりの料理がまだ見つかりませんでした</h2><p>今選んだ食材では、登録レシピに必要な材料が2つ以上足りません。<br>ごはんや追加の調味料も、おうちにあるか確認してみてください。</p></div>';}else{[0,1].forEach(missingCount=>{const items=currentResults.filter(r=>r.missing.length===missingCount);if(!items.length)return;const group=document.createElement('div');group.className='result-group';group.innerHTML=`<h2 class="group-label">${missingCount?'○ あと1つあれば作れる':'◎ 今ある食材で作れる'} <span>${items.length}品</span></h2>`;const cards=document.createElement('div');cards.className='cards';items.forEach(r=>cards.append(makeCard(r)));group.append(cards);root.append(group);});}show('results','results-title');}
function ingredientRows(items,missing){return items.map(i=>`<li><span class="${missing.includes(i.id)?'absent':''}">${i.name}${missing.includes(i.id)?'<small>不足している食材</small>':''}</span><span>${i.amount}</span></li>`).join('');}
function openDetail(result){const r=result.recipe;const root=byId('detail');root.innerHTML=`<p class="eyebrow">03 / レシピを見て、作ってみる</p><div class="detail-top"><img src="${r.image}" alt="${r.title}" width="900" height="600"><div><span class="badge ${result.missing.length?'missing':''}">${statusText(result)}</span><h1 id="detail-title" tabindex="-1">${r.title}</h1><p class="time">調理時間：約${r.time}分 · 2人分</p><div class="status-box ${result.missing.length?'missing':''}">${result.missing.length?`不足している食材：${result.missing.map(id=>names[id]).join('・')}<br>あと${result.missing.map(id=>names[id]).join('・')}があれば作れます。`:'選んだ食材で作れます。材料の分量と基本調味料も確認してね。'}</div></div></div><div class="detail-columns"><div class="recipe-panel"><h2>材料<span class="portion">2人分</span></h2><div class="material-content"><ul class="ingredient-list">${ingredientRows(r.ingredients,result.missing)}</ul><img class="materials-photo" src="assets/ingredients-${r.id}.jpg" alt="${r.title}に使う材料：${r.ingredients.map(i=>i.name).join('、')}" width="600" height="450"></div><h3 class="pantry-title">基本調味料・水</h3><ul class="ingredient-list">${ingredientRows(r.pantry,[])}</ul></div><div class="recipe-panel"><h2>作り方</h2><ol class="steps">${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="point"><strong>おいしく作るポイント</strong>${r.point}</div></div></div><div class="detail-actions"><button id="other-recipes" class="primary">別の料理を見る</button><button id="reselect" class="secondary">食材を選び直す</button></div>`;byId('other-recipes').onclick=()=>show('results','results-title');byId('reselect').onclick=()=>show('selection','main-title');show('detail','detail-title');}
renderIngredients();byId('search').addEventListener('click',searchRecipes);document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>show('selection','main-title')));

function randomizeHero(){const recipe=RECIPES[Math.floor(Math.random()*RECIPES.length)];const image=byId("hero-image");image.src=recipe.image;image.alt=recipe.title;byId("hero-name").textContent=recipe.title;}
randomizeHero();
